services:
  pi_hole:
    container_name: pi_hole
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 8081:80/tcp
      - 443:443/tcp
    environment:
      - TZ=America/Sao_Paulo
      - FTLCONF_webserver_api_password=password
    volumes:
      - ./config/pihole/etc-pihole:/etc/pihole
      - ./config/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped
    dns:
      - 127.0.0.1

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8082:8080
    depends_on:
      - pi_hole

  dashy:
    container_name: dashy
    image: lissy93/dashy:latest
    restart: unless-stopped
    volumes:
      - ./config/dashy/conf.yml:/app/user-data/conf.yml
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - 8083:8080
    depends_on:
      - pi_hole
 
  file_browser:
    container_name: file_browser
    image: filebrowser/filebrowser
    restart: unless-stopped
    volumes:
      - $HOME/remote_docs/share:/srv
      - ./config/file_browser/database.db:/database.db
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - 8084:80
    depends_on:
      - pi_hole

  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    restart: unless-stopped
    volumes:
      - ./config/qbittorrent:/config
      - $HOME/remote_docs/share/wesley/torrent:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=8085
      - TZ=America/Sao_Paulo
      - TORRENTING_PORT=6881
    ports:
      - 8085:8085
      - 6881:6881
      - 6881:6881/udp
    dns:
      - 1.1.1.1

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./config/home_assistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: 'host'
    volumes:
      - ./config/jellyfin/config:/config
      - ./config/jellyfin/cache:/cache
      - type: bind
        source: $HOME/remote_docs/share/wesley/torrent
        target: /media
    restart: 'unless-stopped'
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  # emulatorjs:
  # image: linuxserver/emulatorjs:arm64v8-latest
  # container_name: emulatorjs
  # environment:
  #   - PUID=1000
  #   - PGID=1000
  #   - TZ=America/Sao_Paulo
  #   - SUBFOLDER=/
  #   # - DISABLE_IPFS=true
  # volumes:
  #   - ./config/emulatorjs:/config
  #   - $HOME/remote_docs/share/wesley/roms:/data
  # ports:
  #   - 8087:3000
  #   - 8086:80
  #   - 4001:4001
  # restart: unless-stopped
  # dns:
  #   - 1.1.1.1
